name: trainwise
services:
  api:
    build: ./api
    env_file: .env
    depends_on:
      - redis
      - minio
    networks: [nw]
    expose: ["8001"]

  worker-cpu:
    build: ./worker
    env_file: .env
    depends_on:
      - redis
      - minio
    networks: [nw]

  redis:
    image: redis:7-alpine
    networks: [nw]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    networks: [nw]
    expose:
      - "9000"
      - "9001"

  createbucket:
    image: minio/mc:latest
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "
      mc alias set local ${S3_ENDPOINT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb -p local/${S3_BUCKET} || true &&
      mc anonymous set download local/${S3_BUCKET}/results || true
      "
    networks: [nw]

  nginx:
    build: ./nginx
    env_file: .env
    depends_on: [api]
    ports:
      - "${NGINX_PORT}:80"
    networks: [nw]

networks:
  nw:

volumes:
  minio_data:
